// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_8lshR5MPfwNfEzVVlOqA2ZS_qSrg3gE',
    appId: '1:925661441666:web:658ab3182e44cd472c8e9b',
    messagingSenderId: '925661441666',
    projectId: 'balloon-hunter-6ae47',
    authDomain: 'balloon-hunter-6ae47.firebaseapp.com',
    storageBucket: 'balloon-hunter-6ae47.firebasestorage.app',
    measurementId: 'G-Z3T9EGSEWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfthtL3u9YcqsYZIzGB8DG51luS-IoZfk',
    appId: '1:925661441666:android:ca21e4647c6b0ff22c8e9b',
    messagingSenderId: '925661441666',
    projectId: 'balloon-hunter-6ae47',
    storageBucket: 'balloon-hunter-6ae47.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8hd61x02rAIPdc0oYmjaSMebyZw8apf4',
    appId: '1:925661441666:ios:758c2cbd90856dab2c8e9b',
    messagingSenderId: '925661441666',
    projectId: 'balloon-hunter-6ae47',
    storageBucket: 'balloon-hunter-6ae47.firebasestorage.app',
    androidClientId: '925661441666-2t4r3ckm2qp0sp7nq19u7snf83qebn3j.apps.googleusercontent.com',
    iosClientId: '925661441666-9mb4u5jis92k6a354qoforrup6qdamth.apps.googleusercontent.com',
    iosBundleId: 'com.balloonhunter.balloonHunter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_8lshR5MPfwNfEzVVlOqA2ZS_qSrg3gE',
    appId: '1:925661441666:web:56a5602ed9c3a0d52c8e9b',
    messagingSenderId: '925661441666',
    projectId: 'balloon-hunter-6ae47',
    authDomain: 'balloon-hunter-6ae47.firebaseapp.com',
    storageBucket: 'balloon-hunter-6ae47.firebasestorage.app',
    measurementId: 'G-E3B5CMJ6GK',
  );
}
