final Map<String, String> countryCodes = {
  'AR': 'Argentina',
  'BO': 'Bolivia',
  'BR': 'Brasil',
  'CA': 'Canadá',
  'CL': 'Chile',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'DO': 'República Dominicana',
  'EC': 'Ecuador',
  'SV': 'El Salvador',
  'ES': 'España',
  'US': 'Estados Unidos',
  'GT': 'Guatemala',
  'HN': 'Honduras',
  'MX': 'México',
  'NI': 'Nicaragua',
  'PA': 'Panamá',
  'PY': 'Paraguay',
  'PE': 'Perú',
  'PR': 'Puerto Rico',
  'UY': 'Uruguay',
  'VE': 'Venezuela',
  'DE': 'Alemania',
  'FR': 'Francia',
  'IT': 'Italia',
  'GB': 'Reino Unido',
  'JP': 'Japón',
  'CN': 'China',
  'KR': 'Corea del Sur',
};
